# Generated by Django 2.1.4 on 2019-03-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmoov', '0002_controler_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlertype',
            name='maxPWMPins',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
