# Generated by Django 2.1.4 on 2019-03-02 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmoov', '0002_auto_20190128_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlertype',
            options={'verbose_name': '(Contrôleur) type'},
        ),
        migrations.AlterModelOptions(
            name='ordertype',
            options={'verbose_name': '(Ordre) type'},
        ),
        migrations.AlterModelOptions(
            name='powerline',
            options={'verbose_name': '(Alimentation) ligne'},
        ),
        migrations.AlterModelOptions(
            name='serial',
            options={'verbose_name': '(Série) interface'},
        ),
        migrations.AlterModelOptions(
            name='servotype',
            options={'verbose_name': '(Servo) type'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderType',
        ),
        migrations.AddField(
            model_name='device',
            name='orderType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inmoov.OrderType'),
        ),
    ]
