# Generated by Django 2.1.4 on 2019-03-17 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmoov', '0003_controlertype_maxpwmpins'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speedclass',
            options={'verbose_name': '(Servo) classe de vitesse'},
        ),
        migrations.AddField(
            model_name='order',
            name='speedFactor',
            field=models.PositiveIntegerField(default=0, help_text='0:sans effet , 1:vitesse normale , 2 à 10:facteur de réduction', verbose_name='Facteur de vitesse'),
        ),
        migrations.AlterField(
            model_name='device',
            name='orderType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inmoov.OrderType', verbose_name="type d'ordre"),
        ),
    ]
