# Generated by Django 2.1.4 on 2019-03-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmoov', '0004_auto_20190317_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='speedFactor',
            field=models.PositiveIntegerField(default=0, help_text='0:sans effet | 1:vitesse normale | 2 à 10:facteur de réduction', verbose_name='Facteur de vitesse'),
        ),
    ]
