# Generated by Django 2.1.4 on 2019-03-17 14:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmoov', '0007_device_pintype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='device',
        ),
        migrations.RemoveField(
            model_name='command',
            name='order',
        ),
        migrations.AddField(
            model_name='command',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inmoov.Device'),
        ),
        migrations.AddField(
            model_name='command',
            name='speedFactor',
            field=models.PositiveIntegerField(default=0, help_text='0:sans effet | 1:vitesse normale | 2 à 10:facteur de réduction', validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Facteur de vitesse'),
        ),
        migrations.AddField(
            model_name='command',
            name='value',
            field=models.PositiveIntegerField(blank=True, help_text='valeur envoyée ou pourcentage de la course', null=True, verbose_name='valeur'),
        ),
        migrations.AlterField(
            model_name='device',
            name='pinType',
            field=models.CharField(choices=[('dig', 'Digitale'), ('ana', 'Analogique'), ('unk', 'indéterminé')], default='unk', max_length=3, null=True, verbose_name='type de broche'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
