# Generated by Django 2.1.4 on 2019-03-17 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inmoov', '0008_auto_20190317_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tcpip',
            options={'verbose_name': '(TCP/IP) interface'},
        ),
        migrations.AddField(
            model_name='controler',
            name='sketchName',
            field=models.CharField(blank=True, help_text='nom donné au programme du contrôleur', max_length=50, null=True, verbose_name='Nom du sketch'),
        ),
        migrations.AlterField(
            model_name='device',
            name='index',
            field=models.PositiveIntegerField(help_text='dans les contrôleurs, les équipements sont adressés dans un tableau gérant les broches', null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='accessTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inmoov.Controler', verbose_name='Contrôleur'),
        ),
    ]
